In [1]:
import torch

In [4]:
x = torch.randn(3,requires_grad=True)
x

tensor([-0.1533,  1.0360, -0.1927], requires_grad=True)

In [12]:
y = x.mean()
y

tensor(0.2300, grad_fn=<MeanBackward0>)

In [15]:
# calculate the gradients of y in the backward step
y.backward()
x.grad

tensor([1.3333, 1.3333, 1.3333])

In [21]:
## gradients for vectors
x = torch.randn(3,requires_grad=True)
v = torch.tensor([0.1,1.0,0.001], dtype=torch.float32)
z = x*2
z.backward(v)
print(x.grad,v)


tensor([0.2000, 2.0000, 0.0020]) tensor([0.1000, 1.0000, 0.0010])


# prevennt pytorch from tracking gradients

this can be done by : 
-  x.requires_grad_(False)  : modifies x in place with gradients turned off
-  x.detach() :  returns a copy of x with gradients turned off but x still remains the same
-  with torch.no_grad():  provies a no gradient context

In [22]:
#simple gradient loop

In [25]:
weights = torch.randn(4, requires_grad=True)

for epoch in range(3):
    
    model_output = (weights*3).sum()
    model_output.backward()
    print(f"weights {weights}   gradients: {weights.grad}")

    # empty the gradients for each epoch
    weights.grad.zero_()

weights tensor([-1.1012, -0.7157,  2.2992,  0.3246], requires_grad=True)   gradients: tensor([3., 3., 3., 3.])
weights tensor([-1.1012, -0.7157,  2.2992,  0.3246], requires_grad=True)   gradients: tensor([3., 3., 3., 3.])
weights tensor([-1.1012, -0.7157,  2.2992,  0.3246], requires_grad=True)   gradients: tensor([3., 3., 3., 3.])
